In [1]:
import pandas as pd
import numpy as np

In [2]:
print(pd.__version__)

2.2.3

In [3]:
A = pd.Series([2,3,4,5], index = ['a','b','c','d'])

In [4]:
type(A.values)

numpy.ndarray

In [5]:
type(A)

pandas.core.series.Series

In [6]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
A['a']

np.int64(2)

In [8]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [9]:
grade_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grade_dict)

In [10]:
grads

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [11]:
grads.values

array([4. , 3.5, 3. , 2.5])

In [12]:
marks_dict = {'A':90,'B':80,'C':70,'D':60}
marks = pd.Series(marks_dict)

In [13]:
marks

A    90
B    80
C    70
D    60
dtype: int64

In [14]:
marks[0:2]

A    90
B    80
dtype: int64

In [15]:
marks

A    90
B    80
C    70
D    60
dtype: int64

In [16]:
grads

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [17]:
D = pd.DataFrame({'Marks':marks,'Grades':grads})

In [18]:
D

   Marks  Grades
A     90     4.0
B     80     3.5
C     70     3.0
D     60     2.5

In [19]:
D.T

           A     B     C     D
Marks   90.0  80.0  70.0  60.0
Grades   4.0   3.5   3.0   2.5

In [20]:
D.values

array([[90. ,  4. ],
       [80. ,  3.5],
       [70. ,  3. ],
       [60. ,  2.5]])

In [21]:
D.values[2,0]

np.float64(70.0)

In [22]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [23]:
D

   Marks  Grades
A     90     4.0
B     80     3.5
C     70     3.0
D     60     2.5

In [24]:
D['ScaleMarks'] = 100*(D['Marks']/90)

In [25]:
D

   Marks  Grades  ScaleMarks
A     90     4.0  100.000000
B     80     3.5   88.888889
C     70     3.0   77.777778
D     60     2.5   66.666667

In [26]:
del D['ScaleMarks']

In [27]:
D

   Marks  Grades
A     90     4.0
B     80     3.5
C     70     3.0
D     60     2.5

In [28]:
G = D[D['Marks']>70]

In [29]:
G

   Marks  Grades
A     90     4.0
B     80     3.5

In [30]:
names = {'A':'alan','B':'rony','C':'reem','D':'sedra','E':'omar'}

vaccinated = {'A':"True",'B':"False",'C':"False",'D':"False",'E':"True",}

D = pd.DataFrame({'Names':names,'Vaccinated':vaccinated})
D

   Names Vaccinated
A   alan       True
B   rony      False
C   reem      False
D  sedra      False
E   omar       True

In [31]:
M = D[D['Vaccinated'] == "True"]
M

  Names Vaccinated
A  alan       True
E  omar       True

In [32]:
A = pd.DataFrame([{'a':1, 'b':4},{'b':-3,'c':9}])

In [33]:
A

     a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [34]:
A.fillna(0)

     a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

In [35]:
A.dropna

<bound method DataFrame.dropna of      a  b    c
0  1.0  4  NaN
1  NaN -3  9.0>

In [36]:
A = pd.Series(['a','b','c'], index = [1,3,5])

In [37]:
A[1]

'a'

In [38]:
A[1:3]

3    b
5    c
dtype: object

In [39]:
A.loc[1:3]

1    a
3    b
dtype: object

In [40]:
A.iloc[1:3]

3    b
5    c
dtype: object

In [41]:
D

   Names Vaccinated
A   alan       True
B   rony      False
C   reem      False
D  sedra      False
E   omar       True

In [42]:
D.iloc[2,:]

Names          reem
Vaccinated    False
Name: C, dtype: object

In [43]:
D.iloc[::-1,:]

   Names Vaccinated
E   omar       True
D  sedra      False
C   reem      False
B   rony      False
A   alan       True

In [44]:
df = pd.read_csv(r"C:\Users\Owner\Desktop\AI DATA\Python-Data-Understanding-Data-Visualization-master\Mastering Python for data Understanding and Visualization\adult.data",header=None)

In [45]:
df.shape

(32561, 15)

In [46]:
df.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype='int64')

In [47]:
df.columns = ['C'+str(x) for x in range(df.shape[1])]

In [48]:
df.columns

Index(['C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10',
       'C11', 'C12', 'C13', 'C14'],
      dtype='object')

In [49]:
df['C0']

0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: C0, Length: 32561, dtype: int64

In [50]:
df.loc[:,['C0','C14']]

       C0     C14
0      39   <=50K
1      50   <=50K
2      38   <=50K
3      53   <=50K
4      28   <=50K
...    ..     ...
32556  27   <=50K
32557  40    >50K
32558  58   <=50K
32559  22   <=50K
32560  52    >50K

[32561 rows x 2 columns]

In [51]:
df.head()

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [52]:
L = df['C14'].unique()

In [53]:
L[0]

' <=50K'

In [54]:
L[1]

' >50K'

In [55]:
idx = df['C14'] == L[0]

In [56]:
idx

0         True
1         True
2         True
3         True
4         True
         ...
32556     True
32557    False
32558     True
32559     True
32560    False
Name: C14, Length: 32561, dtype: bool

In [57]:
df['C14'].loc[idx] = -1

C:\Users\Owner\AppData\Local\Temp\ipykernel_21012\3483701917.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['C14'].loc[idx] = -1
C:\Users\Owner\AppData\Local\Temp\ipykernel_21012\3483701917.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['C14'].loc[idx] = -1

In [58]:
df['C14'].loc[~idx] = 1

C:\Users\Owner\AppData\Local\Temp\ipykernel_21012\1980075394.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['C14'].loc[~idx] = 1
C:\Users\Owner\AppData\Local\Temp\ipykernel_21012\1980075394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['C14'].loc[~idx] = 1

In [59]:
df['C14']

0        -1
1        -1
2        -1
3        -1
4        -1
         ..
32556    -1
32557     1
32558    -1
32559    -1
32560     1
Name: C14, Length: 32561, dtype: object

In [60]:
df['C14'].unique()

array([-1, 1], dtype=object)

In [61]:
df.head()

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,-1
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,-1
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,-1
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,-1
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,-1

In [62]:
df['C1'].unique().size

9

In [63]:
df = pd.get_dummies(df, columns=['C1'])

In [64]:
df.shape

(32561, 23)

In [65]:
df.columns

Index(['C0', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11',
       'C12', 'C13', 'C14', 'C1_ ?', 'C1_ Federal-gov', 'C1_ Local-gov',
       'C1_ Never-worked', 'C1_ Private', 'C1_ Self-emp-inc',
       'C1_ Self-emp-not-inc', 'C1_ State-gov', 'C1_ Without-pay'],
      dtype='object')

In [66]:
df = pd.read_csv(r"C:\Users\Owner\Desktop\AI DATA\Python-Data-Understanding-Data-Visualization-master\Mastering Python for data Understanding and Visualization\adult.data",header=None)

In [67]:
df.columns = ['C'+str(x) for x in range(df.shape[1])]

In [68]:
df['C1'].isnull().sum()

np.int64(0)

In [69]:
df['C1'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [70]:
df2 = pd.get_dummies(df,columns=['C1','C14'])

In [71]:
df2.columns

Index(['C0', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11',
       'C12', 'C13', 'C1_ ?', 'C1_ Federal-gov', 'C1_ Local-gov',
       'C1_ Never-worked', 'C1_ Private', 'C1_ Self-emp-inc',
       'C1_ Self-emp-not-inc', 'C1_ State-gov', 'C1_ Without-pay',
       'C14_ <=50K', 'C14_ >50K'],
      dtype='object')

In [72]:
df.isnull().sum()

C0     0
C1     0
C2     0
C3     0
C4     0
C5     0
C6     0
C7     0
C8     0
C9     0
C10    0
C11    0
C12    0
C13    0
C14    0
dtype: int64

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C0      32561 non-null  int64
 1   C1      32561 non-null  object
 2   C2      32561 non-null  int64
 3   C3      32561 non-null  object
 4   C4      32561 non-null  int64
 5   C5      32561 non-null  object
 6   C6      32561 non-null  object
 7   C7      32561 non-null  object
 8   C8      32561 non-null  object
 9   C9      32561 non-null  object
 10  C10     32561 non-null  int64
 11  C11     32561 non-null  int64
 12  C12     32561 non-null  int64
 13  C13     32561 non-null  object
 14  C14     32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [74]:
df2.head()

,C0,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C1_ Federal-gov,C1_ Local-gov,C1_ Never-worked,C1_ Private,C1_ Self-emp-inc,C1_ Self-emp-not-inc,C1_ State-gov,C1_ Without-pay,C14_ <=50K,C14_ >50K
0,39,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,...,False,False,False,False,False,False,True,False,True,False
1,50,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,...,False,False,False,False,False,True,False,False,True,False
2,38,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,...,False,False,False,True,False,False,False,False,True,False
3,53,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,...,False,False,False,True,False,False,False,False,True,False
4,28,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,...,False,False,False,True,False,False,False,False,True,False

In [75]:
df2.to_csv(r"C:\Users\Owner\Desktop\AI DATA\Python-Data-Understanding-Data-Visualization-master\Mastering Python for data Understanding and Visualization\alan.csv")

In [76]:
import pandas as pd

In [77]:
df = pd.DataFrame({'ProductName':['Bulb','Bulb','Fan','Fan'],
                   'Type':['A','B','A','A'],
                  'EC':[400.0,300.0,250.0,300.0]})

In [78]:
df

  ProductName Type     EC
0        Bulb    A  400.0
1        Bulb    B  300.0
2         Fan    A  250.0
3         Fan    A  300.0

In [79]:
df.groupby(['ProductName']).sum()

            Type     EC
ProductName
Bulb          AB  700.0
Fan           AA  550.0

In [80]:
df.groupby([df.Type]).sum()

     ProductName     EC
Type
A     BulbFanFan  950.0
B           Bulb  300.0

In [81]:
df.groupby([df.ProductName,df.Type]).sum()

                     EC
ProductName Type
Bulb        A     400.0
            B     300.0
Fan         A     550.0

In [82]:
#Quiz

names = {'A':'alan ','B':'rony ','C':'reem ','D':'sedra ','E':'omar '}

vaccinated = {'A':"True ",'B':"False ",'C':"True ",'D':"False ",'E':"True ",}

Country = {'A':'China','B':'Pakistan','C':'Pakistan','D':'Pakistan','E':'China'}

D = pd.DataFrame({'Names':names,'Vaccinated':vaccinated, 'Country':Country})

D

# D['Country'] = ['China','Pakistan','Pakistan','Pakistan','China']

D.groupby('Country').sum()

                     Names         Vaccinated
Country
China           alan omar          True True
Pakistan  rony reem sedra   False True False

In [83]:
A = [['Bulb','Bulb','Bulb','Fan','Fan','Fan'],
    ['A','B','C','A','B','C']]
indx = pd.MultiIndex.from_arrays(A,names=('ProductName', 'Type'))
df = pd.DataFrame({'EC':[20,30,40,25,10,30]},index=indx)

In [84]:
df

                  EC
ProductName Type
Bulb        A     20
            B     30
            C     40
Fan         A     25
            B     10
            C     30

In [85]:
df.groupby(level = 0).sum()

             EC
ProductName
Bulb         90
Fan          65

In [86]:
df.groupby(level=1).sum()

      EC
Type
A     45
B     40
C     70

In [87]:
df.groupby(level="ProductName").sum()

             EC
ProductName
Bulb         90
Fan          65

In [ ]:
df = pd.DataFrame({'A':np.random})

In [88]:
df.groupby(level="Type").sum()

      EC
Type
A     45
B     40
C     70

In [89]:
import numpy as np

In [91]:
df = pd.DataFrame({'A':np.random.randint(0,10,5),
                  'B':np.random.randint(0,10,5),
                  'C':np.random.randint(0,10,5)})
df

   A  B  C
0  4  4  6
1  5  1  6
2  3  9  8
3  3  2  0
4  0  2  3

In [94]:
df.rolling(3,min_periods=1).sum()

      A     B     C
0   4.0   4.0   6.0
1   9.0   5.0  12.0
2  12.0  14.0  20.0
3  11.0  12.0  14.0
4   6.0  13.0  11.0

In [95]:
import seaborn as sns

In [96]:
iris = sns.load_dataset('iris')

In [97]:
type(iris)

pandas.core.frame.DataFrame

In [98]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [99]:
df = iris.drop(['species'],axis=1)

In [100]:
df

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [102]:
df.rolling(3,min_periods=1,win_type='gaussian').sum(std=3)

     sepal_length  sepal_width  petal_length  petal_width
0        4.824393     3.310858      1.324343     0.189192
1        9.735201     6.337878      2.724343     0.389192
2       14.170403     9.337928      3.954091     0.578384
3       13.686615     8.970353      4.043282     0.578384
4       13.775807     9.532524      4.054091     0.578384
..            ...          ...           ...          ...
145     19.470453     9.164949     16.200150     6.851414
146     18.997473     8.486565     15.321766     6.462222
147     18.786665     8.175757     14.837978     5.967626
148     18.324493     8.581161     15.037978     5.973030
149     17.929897     9.075757     15.143383     5.894646

[150 rows x 4 columns]

In [105]:
df = pd.DataFrame({'A':[12,4,19,20,35],
                  'B':[1,42,55,61,32],
                  'C':[11,5,13,66,31]})
df

    A   B   C
0  12   1  11
1   4  42   5
2  19  55  13
3  20  61  66
4  35  32  31

In [106]:
df.rolling(3,min_periods=1).sum()

      A      B      C
0  12.0    1.0   11.0
1  16.0   43.0   16.0
2  35.0   98.0   29.0
3  43.0  158.0   84.0
4  74.0  148.0  110.0

In [2]:
import numpy as np

In [3]:
 df = pd.DataFrame(np.arange(10).reshape(5,2),columns = ['A','B'])

In [4]:
df

   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [5]:
df.where(df<5,-df)

   A  B
0  0  1
1  2  3
2  4 -5
3 -6 -7
4 -8 -9

In [9]:
df.where((df<5) | (df%3==3),-df)

   A  B
0  0  1
1  2  3
2  4 -5
3 -6 -7
4 -8 -9

In [10]:
idx = (df<5)|(df%3)

In [11]:
df.where(idx,-df)

   A  B
0  0  1
1  2  3
2  4  5
3 -6  7
4  8 -9

In [14]:
df[~(df<5)] = -df

In [15]:
df

   A  B
0  0 -1
1 -2 -3
2 -4 -5
3 -6 -7
4 -8 -9

In [16]:
df = pd.DataFrame(np.random.randint(0,50,(5,10)),columns=list('ABCDEFGHIJ'))

In [17]:
df

    A   B   C   D   E   F   G   H   I   J
0   7  45  34  46   2  48  24  32   7   0
1  45  33  20  33  34  41  38  14  12  18
2  49  11  35  41  31  14  19  11  43  31
3  45  17  16  42  26  23   9  20   9  42
4  13  28   3  30  23   2  45  14  20  42

In [18]:
df.clip(10,30)

    A   B   C   D   E   F   G   H   I   J
0  10  30  30  30  10  30  24  30  10  10
1  30  30  20  30  30  30  30  14  12  18
2  30  11  30  30  30  14  19  11  30  30
3  30  17  16  30  26  23  10  20  10  30
4  13  28  10  30  23  10  30  14  20  30

In [19]:
df[df<10] = 10
df[df>30] = 30

In [20]:
df

    A   B   C   D   E   F   G   H   I   J
0  10  30  30  30  10  30  24  30  10  10
1  30  30  20  30  30  30  30  14  12  18
2  30  11  30  30  30  14  19  11  30  30
3  30  17  16  30  26  23  10  20  10  30
4  13  28  10  30  23  10  30  14  20  30

In [25]:
df = pd.DataFrame({'A':[12,4,19,20,35],
                  'B':[1,42,55,61,32],
                  'C':[11,5,13,66,31]})
df=df.where((df>10),10)
df=df.where((df<30),30)
# df.clip(10,30)

In [26]:
df

    A   B   C
0  12  10  11
1  10  30  10
2  19  30  13
3  20  30  30
4  30  30  30

In [45]:
df1 = pd.DataFrame({'E':['B','J','L','S'],
                   'G':['A','E','E','H']})
df2 = pd.DataFrame({'E':['L','B','J','S'],
                   'H':[2004,2008,2012,2018]})

In [46]:
print(df1);print(df2)

   E  G
0  B  A
1  J  E
2  L  E
3  S  H
   E     H
0  L  2004
1  B  2008
2  J  2012
3  S  2018

In [47]:
df1

   E  G
0  B  A
1  J  E
2  L  E
3  S  H

In [48]:
df2

   E     H
0  L  2004
1  B  2008
2  J  2012
3  S  2018

In [49]:
[df1,df2]

[   E  G
 0  B  A
 1  J  E
 2  L  E
 3  S  H,
    E     H
 0  L  2004
 1  B  2008
 2  J  2012
 3  S  2018]

In [50]:
pd.merge(df1,df2)

   E  G     H
0  B  A  2008
1  J  E  2012
2  L  E  2004
3  S  H  2018

In [51]:
df3 = pd.merge(df1,df2)
df3

   E  G     H
0  B  A  2008
1  J  E  2012
2  L  E  2004
3  S  H  2018

In [52]:
df4 = pd.DataFrame({'G':['A','E','H'],
                   'S':['C','G','S']})
df4

   G  S
0  A  C
1  E  G
2  H  S

In [58]:
pd.merge(df3,df4,on='G')

   E  G     H  S
0  B  A  2008  C
1  J  E  2012  G
2  L  E  2004  G
3  S  H  2018  S

In [54]:
df5 = pd.DataFrame({'G':['A','A','E','E','H','H'],
                   'Sk':['M','S','C','L','S','O']})
df5

   G Sk
0  A  M
1  A  S
2  E  C
3  E  L
4  H  S
5  H  O

In [55]:
df6 = pd.merge(df3,df4,on='G')

In [57]:
pd.merge(df6,df5,on='G')

   E  G     H  S Sk
0  B  A  2008  C  M
1  B  A  2008  C  S
2  J  E  2012  G  C
3  J  E  2012  G  L
4  L  E  2004  G  C
5  L  E  2004  G  L
6  S  H  2018  S  S
7  S  H  2018  S  O

In [69]:
df1 = pd.DataFrame({'Name':['Anna','Stuart','Alex','Nancy','Robert'],
                   'Subject':['English','Maths','Geography','English','Maths']})

df2 = pd.DataFrame({'Name':['Alex','Robert','Anna','Stuart','Nancy'],
                   'Subject2':['Electronics','Maths','Geography','English','Computer']})
df3 = pd.merge(df1,df2,on='Name')
df3

     Name    Subject     Subject2
0    Anna    English    Geography
1  Stuart      Maths      English
2    Alex  Geography  Electronics
3   Nancy    English     Computer
4  Robert      Maths        Maths

In [2]:
from seaborn import load_dataset

In [36]:
T = load_dataset('titanic')

In [37]:
T.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [38]:
T.rename(columns={'sex':'Gender'},inplace=True)

In [39]:
T.head()

,survived,pclass,Gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [40]:
T.deck.isnull().sum()

np.int64(688)

In [41]:
T.drop(['deck'],axis=1,inplace=True)

In [42]:
T.head()

,survived,pclass,Gender,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [43]:
T.groupby(['Gender','pclass'])['survived'].mean().unstack()

pclass         1         2         3
Gender
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [44]:
T.pivot_table('survived',index='Gender',columns='pclass',aggfunc='mean')

pclass         1         2         3
Gender
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [45]:
agePartitions = pd.cut(T['age'],[0,18,80])

In [46]:
agePartitions

0      (18.0, 80.0]
1      (18.0, 80.0]
2      (18.0, 80.0]
3      (18.0, 80.0]
4      (18.0, 80.0]
           ...
886    (18.0, 80.0]
887    (18.0, 80.0]
888             NaN
889    (18.0, 80.0]
890    (18.0, 80.0]
Name: age, Length: 891, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 80]]

In [47]:
T.pivot_table('survived',['Gender', agePartitions],'pclass')

C:\Users\Owner\AppData\Local\Temp\ipykernel_11364\48394386.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  T.pivot_table('survived',['Gender', agePartitions],'pclass')

pclass                  1         2         3
Gender age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [48]:
farePartitions = pd.qcut(T['fare'],2)

In [49]:
T.pivot_table('survived',['Gender',agePartitions],[farePartitions,'pclass'])

C:\Users\Owner\AppData\Local\Temp\ipykernel_11364\1900208485.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  T.pivot_table('survived',['Gender',agePartitions],[farePartitions,'pclass'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
pclass                         1         2         3                 1
Gender age
female (0, 18]               NaN  1.000000  0.714286          0.909091
       (18, 80]              NaN  0.880000  0.444444          0.972973
male   (0, 18]               NaN  0.000000  0.260870          0.800000
       (18, 80]              0.0  0.098039  0.125000          0.391304

fare
pclass                  2         3
Gender age
female (0, 18]   1.000000  0.318182
       (18, 80]  0.914286  0.391304
male   (0, 18]   0.818182  0.178571
       (18, 80]  0.030303  0.192308

In [50]:
T.pivot_table(index='Gender',columns='pclass',aggfunc={'survived':sum,'fare':'mean'})

C:\Users\Owner\AppData\Local\Temp\ipykernel_11364\1683064886.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  T.pivot_table(index='Gender',columns='pclass',aggfunc={'survived':sum,'fare':'mean'})

              fare                       survived
pclass           1          2          3        1   2   3
Gender
female  106.125798  21.970121  16.118810       91  70  72
male     67.226127  19.741782  12.661633       45  17  47

In [51]:
T.head()

,survived,pclass,Gender,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [52]:
T.Gender.str.capitalize()

0        Male
1      Female
2      Female
3      Female
4        Male
        ...
886      Male
887    Female
888    Female
889      Male
890      Male
Name: Gender, Length: 891, dtype: object

In [53]:
T.head()

,survived,pclass,Gender,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [55]:
T.Gender.str.cat(T.embark_town)

0        maleSouthampton
1        femaleCherbourg
2      femaleSouthampton
3      femaleSouthampton
4        maleSouthampton
             ...
886      maleSouthampton
887    femaleSouthampton
888    femaleSouthampton
889        maleCherbourg
890       maleQueenstown
Name: Gender, Length: 891, dtype: object

In [56]:
T.embark_town.isnull().sum()

np.int64(2)

In [57]:
"abc,ghj,rew".split(',')

['abc', 'ghj', 'rew']

In [2]:
from datetime import datetime

In [3]:
dates = pd.to_datetime([datetime(2010,7,3),'10th of July,2018','2017-July-19'
                       ,'10-09-2016','20160305'])

In [4]:
dates

DatetimeIndex(['2010-07-03', '2018-07-10', '2017-07-19', '2016-10-09',
               '2016-03-05'],
              dtype='datetime64[ns]', freq=None)

In [5]:
dates.to_period('D')

PeriodIndex(['2010-07-03', '2018-07-10', '2017-07-19', '2016-10-09',
             '2016-03-05'],
            dtype='period[D]')

In [6]:
dates-dates[0]

TimedeltaIndex(['0 days', '2929 days', '2573 days', '2290 days', '2072 days'], dtype='timedelta64[ns]', freq=None)